openapi: 3.1.0
info:
  title: Prove OpenAPI definition
  version: v1.0.0
servers:
  - url: https://api.staging.payfone.com
    description: Sandbox server (uses test data)
  - url: https://api.payfone.com
    description: Production server
tags:
  - name: Mobile Auth
    description: Operations or actions related to a mobile authentication.
paths:
  /mobileauth/2014/07/01/authenticateByRedirectFinish:
    post:
      summary: Authenticate by Redirect Finish
      description: >
        This endpoint finishes the Mobile Auth process by passing the second verification fingerprint, returned from the carrier call on the device, to then—if successful—receive the consumer's Payfone Alias and mobile number.
      operationId: authByRedirectFinish
      x-speakeasy-name-override: authByRedirectFinish
      tags:
        - Mobile Auth
      x-speakeasy-group: Mobile Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedirectFinishRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectFinishResponse'
components:
  schemas:
    RedirectFinishResponse:
      type: object
      properties:
        RequestId:
          type: string
          example: "7f83-b0c4-90e0-90b3-11e10800200c9a66"
          description: The requestId from the request, reflected back for tracking purposes.
        Status:
          type: integer
          example: 0
          description: The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
        Description:
          type: string
          example: "Success."
          description: A text string that defines the cause of the status code.
        Response:
          type: object
          properties:
            AuthenticateFinishTransactionId:
              type: string
              example: "144356671"
              description: A unique identifier generated by Prove that can be used to troubleshoot any problems with this transaction.
            PayfoneAlias:
              type: string
              example: "C24C4C54DR10481C4E0U44ERMVUP9S1TUNXPLA2T753ETMCFOA086TYMCAQL00B4E0CLC4C24BHZPO4QWPN68EAV14ERTVPMMEP7OCXTRBQR17YERTMK749"
              description: A persistent ID that uniquely identifies a telephone subscriber.
            AuthenticationCode:
              type: string
              example: "F22440010AC782406249CFE0560F68EF"
              description: A transaction ID denoting the authentication event.
            AuthenticationExpiration:
              type: string
              example: "2017-10-03T17:48:18.000Z"
              description: The expiration timestamp in UTC of the authentication code. Timestamp is in ISO-8601 format.
            MobileNumber:
              type: string
              example: "15553031212"
              description: The phone number of the originating phone.
            MobileCountryCode:
              type: string
              example: "310"
              description: The country code associated with this phone number.
            MobileOperatorName:
              type: string
              example: "Verizon"
              description: The carrier related to the phone number.
    RedirectFinishRequest:
      type: object
      required:
        - requestId
        - apiClientId
        - verificationFingerprint
      properties:
        requestId:
          type: string
          example: "7f8390e0-90b3-11e1-b0c4-0800200c9a66"
          description: >
            Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
        apiClientId:
          type: string
          example: "C6f1j294x70dY3l76xU6"
          description: Prove-issued unique, private key that identifies the API Client.
        subClientId:
          type: string
          example: "ThisIsMyCustomerId222"
          description: Prove-issued unique, private key that identifies Sub Client.
        verificationFingerprint:
          type: string
          example: "F22440010AC782406249CFE0560F68EF"
          description: The VFP value returned by the mobile device after authentication.
