openapi: 3.1.0
info:
  title: Prove OpenAPI definition
  version: v1.0.0
servers:
  - url: https://api.staging.payfone.com
    description: Sandbox server (uses test data)
  - url: https://api.payfone.com
    description: Production server
tags:
  - name: Mobile Auth
    description: Operations or actions related to a mobile authentication.
paths:
  /mobileauth/2014/07/01/authenticateByRedirect:
    post:
      summary: Authenticate by Redirect
      description: >
        This endpoint starts the Mobile Auth process by passing the IP for the device in question to be authenticated—along with the final URL the consumer will be directed to—and then returning a redirect URL appended to the first verification fingerprint in the response.
      operationId: authByRedirect
      x-speakeasy-name-override: authByRedirect
      tags:
        - Mobile Auth
      x-speakeasy-group: Mobile Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedirectRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectResponse'
components:
  schemas:
    RedirectResponse:
      type: object
      properties:
        RequestId:
          type: string
          example: "7f83-b0c4-90e0-90b3-11e10800200c9a66"
          description: The requestId from the request, reflected back for tracking purposes.
        Status:
          type: integer
          example: 0
          description: The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
        Description:
          type: string
          example: "Success."
          description: A text string that defines the cause of the status code.
        Response:
          type: object
          properties:
            AuthenticateTransactionId:
              type: string
              example: "e18f743e-a1b7-4d12-b8a7-a3569a76b110"
              description: A unique identifier generated by Prove that can be used to troubleshoot any problems with this transaction.
            RedirectTargetUrl:
              type: string
              example: "http://device.staging.payfone.com/mobileauth/2014/07/01/deviceAuthenticate?vfp=4e4759784e5755334d6d49744d546b794d4330304d4455314c5749774d7a45745a6a646d5a5445354d3249794d47553566444238524877783a83a827abfafbf2231685927f651934de3c988ac3f15bb76a6373ce593a68f417"
              description: If the phone is eligible for authentication, this field will contain the URL that the phone should be redirected to authenticate the phone. Max length returned is 2048 bytes.
    RedirectRequest:
      type: object
      required:
        - consentStatus
        - requestId
        - apiClientId
        - finalTargetUrl
        - deviceIp
      properties:
        requestId:
          type: string
          example: "7f83-b0c4-90e0-90b3-11e10800200c9a66"
          description: Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
        apiClientId:
          type: string
          example: "C6f1j294x70dY3l76xU6"
          description: Prove-issued unique, private key that identifies the API Client.
        subClientId:
          type: string
          example: "D6hy5294x70dY3l76xU6"
          description: Prove-issued unique, private key that identifies Sub Client.
        finalTargetUrl:
          type: string
          example: "http://www.google.com"
          description: The URL of the client server that will be called back by the phone, providing the VFP for the result call.
        mobileNetworkOperator:
          type: string
          example: "T-Mobile"
          description: 'The mobile network operator that currently operates the phone number. Internal note: This is a legacy parameter and is no longer used.'
        deviceIp:
          type: string
          example: "2607:fb90:be01:4122:e118:813f:736a:b7b9"
          description: The IP address of the mobile device to be authenticated.
        subscriptionCustomerId:
          type: string
          example: "ThisIsMyCustomerId222"
          description: A unique identifier for our customer's subscribers for Identity Manager.
        consentStatus:
          $ref: './common/components.yaml#/components/schemas/consentStatus'
        consentTransactionId:
          type: string
          example: "EWSrelease-01092020-testTMO5"
          description: Uniquely identify the consent collected by the client. **Required** if `ConsentStatus` = `optedIn`
        consentDescription:
          type: string
          example: "Test Description"
          description: The client describes the type of consent (electronic/paper), use case and reference to the version of Terms and Conditions (T&Cs), if applicable. **Required** if `ConsentStatus` = `optedIn`
        consentCollectedTimestamp:
          type: string
          example: "2022-05-11"
          description: Date/Time field where the original consent was collected by the client. The string format is YYYY-MM-DD. **Required** if `ConsentStatus` = `optedIn`
