openapi: 3.1.0
info:
  title: Prove OpenAPI definition
  version: v1.0.0
servers:
  - url: https://api.staging.payfone.com
    description: Sandbox server (uses test data)
  - url: https://api.payfone.com
    description: Production server
tags:
  - name: Instant Link
    description: Operations or actions related to retrieving an Instant Link.
paths:
  /fortified/2015/06/01/instantLinkResult:
    post:
      summary: Instant Link Result
      description: >
        To complete the Instant Link flow, this endpoint passes the second, unique verification fingerprint returned by the mobile device, and identifies whether Instant Link was completed with or without carrier authentication, whether the link was clicked within the expiration time, and whether the input device was where the link was clicked.
      operationId: getResult
      x-speakeasy-name-override: getResult
      tags:
        - Instant Link
      x-speakeasy-group: Instant Link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstantLinkRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstantLinkResponse'
components:
  schemas:
    InstantLinkResponse:
      type: object
      properties:
        RequestId:
          type: string
          example: "7f83-b0c4-90e0-90b3-11e10800200c9a66"
          description: The requestId from the request, reflected back for tracking purposes.
        Status:
          type: integer
          example: 0
          description: The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
        Description:
          type: string
          example: "Success."
          description: A text string that defines the cause of the status code.
        Response:
          type: object
          properties:
            TransactionId:
              type: string
              example: "163657716"
              description: Unique transaction identifier used to identify the results of the request.
            PhoneNumber:
              type: string
              example: "13478035027"
              description: The phone number of the originating phone
            Carrier:
              type: string
              example: "Verizon"
              description: The carrier related to the phone number
            LineType:
              type: string
              example: "Mobile"
              description: 'Line type associated with the phone number. Possible values are: Mobile, Landline, FixedVoIP, NonFixedVoIP'
            CountryCode:
              type: string
              example: "US"
              description: The country code associated with the phone number
            LinkClicked:
              type: string
              example: "0"
              description: 'Indicates whether the link was clicked within the expiration time. Possible values are: 1 (clicked), 0 (not clicked)'
            PhoneMatch:
              type: string
              example: "indeterminate"
              description: 'Indicates whether the link was clicked within the expiration time. Possible values are: 1 (clicked), 0 (not clicked)'
            IpAddressMatch:
              type: boolean
              example: true
              description: Boolean informing as to whether the link was clicked on the device that has the same public IP address as the web application that started the Instant Link process.<br><br>The goal is to understand if the application visitor is on the same network as the person who received and clicked on the instant link on the mobile device.
            SessionId:
              type: string
              example: "0109083438"
              description: Session identifier associated with this request flow. It should be the same session ID as the /getAuthUrl call.
            DeviceIp:
              type: string
              example: "10.1.68.167"
              description: An optional output (must be configured at the merchant level and not available for all customers) that returns the device's IP where the link was clicked. This can be compared to the sourceIp submitted in the /getAuthUrl call.
    InstantLinkRequest:
      type: object
      required:
        - requestId
        - sessionId
        - apiClientId
        - verificationFingerprint
      properties:
        SessionId:
          type: string
          example: "0109083438"
          description: Session identifier associated with this request flow. It should be the same session ID as the /getAuthUrl call.
        RequestId:
          type: string
          example: "7f83-b0c4-90e0-90b3-11e10800200c9a66"
          description: The requestId from the request, reflected back for tracking purposes.
        apiClientId: 
          type: string
          example: "C6f1j294x70dY3l76xU6"
          description: Prove-issued unique, private key that identifies the API Client.
        subClientId: 
          type: string
          example: "G6x1j294x70dY3l76xU6"
          description: Prove-issued unique, private key that identifies the API Client.
        VerificationFingerprint:
          type: string
          example: "F22440010AC782406249CFE0560F68EF"
          description: The second, unique verification fingerprint returned by the mobile device
