openapi: 3.1.0
info:
  title: Prove OpenAPI definition
  version: v1.0.0
servers:
  - url: https://api.staging.payfone.com
    description: Sandbox server (uses test data)
  - url: https://api.payfone.com
    description: Production server
security:
    - bearerAuth: []
tags:
  - name: Trust
    description: Operations or actions related to Trust score
paths:
  /trust/v2:
    post:
      summary: Trust Score
      description: This endpoint queries the consumer's phone number (or PayfoneAlias) to return a Prove Trust Score and, potentially, other attributes to indicate the trustworthiness of a phone number and its identity.
      operationId: getScore
      x-speakeasy-name-override: getScore
      tags:
        - Trust
      x-speakeasy-group: Trust
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoreRequest'
      responses:
        '200':
          description: Success - consentStatus=optedIn, details=true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ScoreResponse:
      type: object
      properties:
        requestId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          description: The requestId from the request, reflected back for tracking purposes.
        status:
          type: integer
          example: 0
          description: The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
        description:
          type: string
          example: Success.
          description: A text string that defines the cause of the status code.
        response:
          type: object
          properties:
            transactionId:
              type: string
              example: '163657716'
              description: Unique transaction identifier used to identify the results of the request.
            payfoneAlias:
              type: string
              example: 666666664VKDEO11BC3EA0450A73013050MEK19P4SF9P89BF3C331880A3075A816A65D1A1390BD5AF6G31EE0B804104A5B04E7FC8B88FE226E03FB02
              description: A persistent ID that uniquely identifies a telephone subscriber.
            phoneNumber:
              type: string
              example: '13478035027'
              description: The phone number associated with the subscriber.
            lineType:
              type: string
              example: Mobile
              description: 'Line type associated with the phone number. Possible values are: Mobile, Landline, FixedVoIP, NonFixedVoIP'
            carrier:
              type: string
              example: Verizon
              description: The carrier related to the phone number.
            countryCode:
              type: string
              example: US
              description: The country code associated with the phone number
            statusIndex:
              type: string
              example: '11'
              description: A bitmapped value that represents networkStatus, accountType, accountRole, and customerType. For more information, see the Trust Score Integration Guide.
            isBaselined:
              type: boolean
              example: true
              description: An indicator to communicate whether Prove has ever transacted with the input phone number before the current transaction.
            trustScore:
              type: integer
              example: 892
              description: An integer value ranging from 0–1000 denotes the real-time trustworthiness of a phone number. 1000 indicates perfect trust, while 0 indicates a complete lack of trust. For more information on Trust Score, see the Trust Score Integration Guide.
            reasonCodes:
              type: array
              description: 'An array of indicators provide additional context about the transaction. See Reason Codes Reference Information for detailed reason codes.'
              items:
                type: string
                example: "CU"
            carrierStatus:
              type: string
              example: UNKNOWN
              description: 'The current phone number network status associated with the carriers. Values include: Active, Suspended, Disconnected, Unknown'
            phoneNumberVelocity:
              type: integer
              example: 0
              description: The number of times the subscriber has changed their phone number.
            portVelocity:
              type: integer
              example: 1
              description: The number of times the subscriber has changed their carrier within the last 90 days.
            simVelocity:
              type: integer
              example: 0
              description: The number of times the mobile subscriber has changed their device within the last 90 days.
            deviceVelocity:
              type: integer
              example: 0
              description: The number of times the mobile subscriber has changed their device within the last 90 days.
            payfoneTenure:
              type: object
              description: The amount of time Prove has been able to track the subscriber. Defined with a minimum and maximum date.
              properties:
                minimumDate:
                  type: string
                  format: date-time
                  example: '2021-11-21T23:59:59.000Z'
            carrierTenure:
              type: object
              description: The amount of time Prove has been able to track the carrier associated with the subscriber. Defined with a minimum and maximum date.
              properties:
                minimumDate:
                  type: string
                  format: date-time
                  example: '2022-11-14T23:59:59.000Z'
                maximumDate:
                  type: string
                  format: date-time
                  example: '2022-10-22T00:00:00.000Z'
            phoneNumberTenure:
              type: object
              description: The amount of time Prove has been able to track the phone number associated with the subscriber. Defined with a minimum and maximum date.
              properties:
                minimumDate:
                  type: string
                  format: date-time
                  example: '2021-11-21T23:59:59.000Z'
            simTenure:
              type: object
              description: The amount of time Prove has been able to track the SIM association with the subscriber. Defined with a minimum and maximum date.
              properties:
                minimumDate:
                  type: string
                  format: date-time
                  example: '2022-11-14T23:59:59.000Z'
                maximumDate:
                  type: string
                  format: date-time
                  example: '2022-10-22T00:00:00.000Z'
            deviceTenure:
              type: object
              description: The amount of time Prove has been able to track the device association with the subscriber. Defined with a minimum and maximum date.
              properties:
                minimumDate:
                  type: string
                  format: date-time
                  example: '2022-11-14T23:59:59.000Z'
                maximumDate:
                  type: string
                  format: date-time
                  example: '2022-10-22T00:00:00.000Z'
            portedDate:
              type: object
              description: The date associated with a port of the phone number. Defined with a minimum and maximum date.
              properties:
                minimumDate:
                  type: string
                  format: date-time
                  example: '2022-10-28T22:25:00.000Z'
                maximumDate:
                  type: string
                  format: date-time
                  example: '2022-10-28T22:25:00.000Z'
    ScoreRequest:
      required:
        - consentStatus
        - requestId
        - phoneNumber
      type: object
      properties:
        requestId:
          type: string
          example: '59c04ea5-5aae-4934-a96f-f32051f5078b'
          description: Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
        payfoneAlias:
          type: string
          example: FB9990AC4VKRKKX801F617431E9C9B5D10MEK1KQZ3T9PCC265D01B991F09559712BEF30B7115C258F6G38FB0EF56226588191F2011FF1246401DF6B6
          description: A persistent ID that uniquely identifies a telephone subscriber. A phoneNumber or payfoneAlias is required in the request, not both.
        consentStatus:
          $ref: './common/components.yaml#/components/schemas/consentStatus'
        phoneNumber:
          type: string
          example: '8167434789'
          description: The phone number being queried. Formatted in E.164 formatting for international numbers including the leading plus sign.
        details:
          type: string
          example: 'true'
          description: True indicates whether the client is accessing premium data responses. See Response Definitions for examples with and without details.
        subscriptionCustomerId:
          type: string
          example: ThisIsMyCustomerId222
          description: A unique identifier for our customer's subscribers for Identity Manager.