// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/prove-go/pkg/models/shared"
	"net/http"
)

type AuthByRedirectResponse struct {
	ContentType string
	// Success
	RedirectResponse *shared.RedirectResponse
	StatusCode       int
	RawResponse      *http.Response
}
