// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/prove-go/pkg/models/shared"
	"net/http"
)

type GetAuthURLResponse struct {
	// Success
	AuthURLResponse *shared.AuthURLResponse
	ContentType     string
	StatusCode      int
	RawResponse     *http.Response
}
