// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/prove-go/pkg/models/shared"
	"net/http"
)

type GetResultResponse struct {
	ContentType string
	// Success
	InstantLinkResponse *shared.InstantLinkResponse
	StatusCode          int
	RawResponse         *http.Response
}
