// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/prove-go/pkg/models/shared"
	"net/http"
)

type VerifyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success - details=true + identifiers submitted
	VerifyResponse *shared.VerifyResponse
}
