// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AuthURLResponseResponse struct {
	// Fortified URL to be sent via SMS to the mobile device to be clicked on by the device to be authenticated. The max length returned is 2048 bytes.
	AuthenticationURL *string `json:"AuthenticationUrl,omitempty"`
	// The carrier related to the phone number.
	MobileOperatorName *string `json:"MobileOperatorName,omitempty"`
}

// AuthURLResponse - Success
type AuthURLResponse struct {
	// A text string that defines the cause of the status code.
	Description *string `json:"Description,omitempty"`
	// The requestId from the request, reflected back for tracking purposes.
	RequestID *string                  `json:"RequestId,omitempty"`
	Response  *AuthURLResponseResponse `json:"Response,omitempty"`
	// The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
	Status *int64 `json:"Status,omitempty"`
}
