// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AuthURLRequest struct {
	// Prove-issued unique, private key that identifies the API Client.
	APIClientID string `json:"apiClientId"`
	// The URL of the client server that will be called back by the phone, providing the VFP for the result call.
	FinalTargetURL string `json:"finalTargetUrl"`
	// The mobile number that is being sent the SMS link. Formatted in E.164 formatting for international numbers including the leading plus sign.
	MobileNumber string `json:"mobileNumber"`
	// Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
	RequestID string `json:"requestId"`
	// Session identifier associated with this request. Max length is 128 bytes.
	SessionID string `json:"sessionId"`
	// The IP address of the device the request initiates from. This adds an additional fraud detection indicator, as Prove can use this value to complete an IP comparison with the IP of the device that actually clicks the link sent.
	SourceIP *string `json:"sourceIp,omitempty"`
	// Prove-issued unique, private key that identifies Sub Client.
	SubClientID *string `json:"subClientId,omitempty"`
	// A unique identifier for our customer's subscribers for Identity Manager.
	SubscriptionCustomerID *string `json:"subscriptionCustomerId,omitempty"`
}
