// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ConsentStatus - Denotes whether consent has been provided by the mobile subscriber for this transaction. Acceptable values are:
// - `optedIn` - The end user has provided consent for the collection of their personal data. - `optedOut` - The end user has refused to allow collection of their personal data. - `notCollected` - No attempt has been made to obtain consent from the end user. - `unknown` - The status of consent collection is unknown.
// Note: This value must be optedIn in order to access MNO data. Legacy customers' configurations are not affected by this requirement at this time.
type ConsentStatus string

const (
	ConsentStatusOptedIn      ConsentStatus = "optedIn"
	ConsentStatusOptedOut     ConsentStatus = "optedOut"
	ConsentStatusNotCollected ConsentStatus = "notCollected"
	ConsentStatusUnknown      ConsentStatus = "unknown"
)

func (e ConsentStatus) ToPointer() *ConsentStatus {
	return &e
}

func (e *ConsentStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "optedIn":
		fallthrough
	case "optedOut":
		fallthrough
	case "notCollected":
		fallthrough
	case "unknown":
		*e = ConsentStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConsentStatus: %v", v)
	}
}
