// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IdentityResponseResponseIndividualAddresses struct {
	// The primary address line. Usually populated.
	Address *string `json:"address,omitempty"`
	// The city where the address is located.
	City *string `json:"city,omitempty"`
	// The secondary address line. Populated for suites, apartments, boxes, departments, etc.
	ExtendedAddress *string `json:"extendedAddress,omitempty"`
	// The postal/zip code of the address.
	PostalCode *string `json:"postalCode,omitempty"`
	// The region or state where the address is located.
	Region *string `json:"region,omitempty"`
}

type IdentityResponseResponseIndividual struct {
	// Physical address(es) that are associated with the phone number.
	Addresses []IdentityResponseResponseIndividualAddresses `json:"addresses,omitempty"`
	// Date of birth in ISO 8601 format (YYYY-MM-DD)
	Dob *string `json:"dob,omitempty"`
	// The email address(es) associated with this phone number. This is a premium data field; if you are interested in access, please speak with your account manager.
	EmailAddresses []string `json:"emailAddresses,omitempty"`
	// The first name of the person
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the person
	LastName *string `json:"lastName,omitempty"`
	// Social security number
	Ssn *string `json:"ssn,omitempty"`
}

type IdentityResponseResponse struct {
	// The carrier related to the phone number.
	Carrier *string `json:"carrier,omitempty"`
	// The country code associated with the phone number
	CountryCode *string                             `json:"countryCode,omitempty"`
	Individual  *IdentityResponseResponseIndividual `json:"individual,omitempty"`
	// Line type associated with the phone number. Possible values are: Mobile, Landline, FixedVoIP, NonFixedVoIP
	LineType *string `json:"lineType,omitempty"`
	// The phone number associated with the subscriber.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// An array of indicators provide additional context about the transaction. See Reason Codes Reference Information for detailed reason codes.
	ReasonCodes []string `json:"reasonCodes,omitempty"`
	// Unique transaction identifier used to identify the results of the request.
	TransactionID *string `json:"transactionId,omitempty"`
}

// IdentityResponse - Success
type IdentityResponse struct {
	// A text string that defines the cause of the status code.
	Description *string `json:"description,omitempty"`
	// The requestId from the request, reflected back for tracking purposes.
	RequestID *string                   `json:"requestId,omitempty"`
	Response  *IdentityResponseResponse `json:"response,omitempty"`
	// The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
	Status *int64 `json:"status,omitempty"`
}
