// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IdentityRequest struct {
	// Denotes whether consent has been provided by the mobile subscriber for this transaction. Acceptable values are:
	// - `optedIn` - The end user has provided consent for the collection of their personal data. - `optedOut` - The end user has refused to allow collection of their personal data. - `notCollected` - No attempt has been made to obtain consent from the end user. - `unknown` - The status of consent collection is unknown.
	// Note: This value must be optedIn in order to access MNO data. Legacy customers' configurations are not affected by this requirement at this time.
	ConsentStatus ConsentStatus `json:"consentStatus"`
	// Date of birth associated with the phone number. Three different styles are allowed; ISO 8601 format for full DOB (YYYY-MM-DD), month and year (mm/yyyy) or month and day (mm/dd). In order to access DOB and SSN data for a phone number, you must supply in the request the DOB, partial SSN, or full SSN.
	Dob *string `json:"dob,omitempty"`
	// Last four of the social security number associated with the phone number.
	Last4 *string `json:"last4,omitempty"`
	// The desired number of addresses to return. The default and recommended amount is 3; more could affect your service level. The maximum possible is 10.
	NumberOfAddresses *string `json:"numberOfAddresses,omitempty"`
	// The desired number of email addresses to return. The default and recommended amount is 3; more could affect your service level. The maximum possible is 10.
	NumberOfEmails *string `json:"numberOfEmails,omitempty"`
	// The phone number being queried. Formatted in E.164 formatting for international numbers including the leading plus sign.
	PhoneNumber string `json:"phoneNumber"`
	// Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
	RequestID string `json:"requestId"`
	// The social security number associated with the phone number (#########)
	Ssn *string `json:"ssn,omitempty"`
	// A unique identifier for our customer's subscribers for Identity Manager.
	SubscriptionCustomerID *string `json:"subscriptionCustomerId,omitempty"`
	// Internal only: When set to true, Trust Score is called.
	TrustScore *string `json:"trustScore,omitempty"`
}
