// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type InstantLinkResponseResponse struct {
	// The carrier related to the phone number
	Carrier *string `json:"Carrier,omitempty"`
	// The country code associated with the phone number
	CountryCode *string `json:"CountryCode,omitempty"`
	// An optional output (must be configured at the merchant level and not available for all customers) that returns the device's IP where the link was clicked. This can be compared to the sourceIp submitted in the /getAuthUrl call.
	DeviceIP *string `json:"DeviceIp,omitempty"`
	// Boolean informing as to whether the link was clicked on the device that has the same public IP address as the web application that started the Instant Link process.<br><br>The goal is to understand if the application visitor is on the same network as the person who received and clicked on the instant link on the mobile device.
	IPAddressMatch *bool `json:"IpAddressMatch,omitempty"`
	// Line type associated with the phone number. Possible values are: Mobile, Landline, FixedVoIP, NonFixedVoIP
	LineType *string `json:"LineType,omitempty"`
	// Indicates whether the link was clicked within the expiration time. Possible values are: 1 (clicked), 0 (not clicked)
	LinkClicked *string `json:"LinkClicked,omitempty"`
	// Indicates whether the link was clicked within the expiration time. Possible values are: 1 (clicked), 0 (not clicked)
	PhoneMatch *string `json:"PhoneMatch,omitempty"`
	// The phone number of the originating phone
	PhoneNumber *string `json:"PhoneNumber,omitempty"`
	// Session identifier associated with this request flow. It should be the same session ID as the /getAuthUrl call.
	SessionID *string `json:"SessionId,omitempty"`
	// Unique transaction identifier used to identify the results of the request.
	TransactionID *string `json:"TransactionId,omitempty"`
}

// InstantLinkResponse - Success
type InstantLinkResponse struct {
	// A text string that defines the cause of the status code.
	Description *string `json:"Description,omitempty"`
	// The requestId from the request, reflected back for tracking purposes.
	RequestID *string                      `json:"RequestId,omitempty"`
	Response  *InstantLinkResponseResponse `json:"Response,omitempty"`
	// The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
	Status *int64 `json:"Status,omitempty"`
}
