// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RedirectResponseResponse struct {
	// A unique identifier generated by Prove that can be used to troubleshoot any problems with this transaction.
	AuthenticateTransactionID *string `json:"AuthenticateTransactionId,omitempty"`
	// If the phone is eligible for authentication, this field will contain the URL that the phone should be redirected to authenticate the phone. Max length returned is 2048 bytes.
	RedirectTargetURL *string `json:"RedirectTargetUrl,omitempty"`
}

// RedirectResponse - Success
type RedirectResponse struct {
	// A text string that defines the cause of the status code.
	Description *string `json:"Description,omitempty"`
	// The requestId from the request, reflected back for tracking purposes.
	RequestID *string                   `json:"RequestId,omitempty"`
	Response  *RedirectResponseResponse `json:"Response,omitempty"`
	// The status of the request. A response of 0 indicates success. Any non-0 response is an error indication. For more information on status codes, see the Error and Status Codes section.
	Status *int64 `json:"Status,omitempty"`
}
