// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RedirectRequest struct {
	// Prove-issued unique, private key that identifies the API Client.
	APIClientID string `json:"apiClientId"`
	// Date/Time field where the original consent was collected by the client. The string format is YYYY-MM-DD. **Required** if `ConsentStatus` = `optedIn`
	ConsentCollectedTimestamp *string `json:"consentCollectedTimestamp,omitempty"`
	// The client describes the type of consent (electronic/paper), use case and reference to the version of Terms and Conditions (T&Cs), if applicable. **Required** if `ConsentStatus` = `optedIn`
	ConsentDescription *string `json:"consentDescription,omitempty"`
	// Denotes whether consent has been provided by the mobile subscriber for this transaction. Acceptable values are:
	// - `optedIn` - The end user has provided consent for the collection of their personal data. - `optedOut` - The end user has refused to allow collection of their personal data. - `notCollected` - No attempt has been made to obtain consent from the end user. - `unknown` - The status of consent collection is unknown.
	// Note: This value must be optedIn in order to access MNO data. Legacy customers' configurations are not affected by this requirement at this time.
	ConsentStatus ConsentStatus `json:"consentStatus"`
	// Uniquely identify the consent collected by the client. **Required** if `ConsentStatus` = `optedIn`
	ConsentTransactionID *string `json:"consentTransactionId,omitempty"`
	// The IP address of the mobile device to be authenticated.
	DeviceIP string `json:"deviceIp"`
	// The URL of the client server that will be called back by the phone, providing the VFP for the result call.
	FinalTargetURL string `json:"finalTargetUrl"`
	// The mobile network operator that currently operates the phone number. Internal note: This is a legacy parameter and is no longer used.
	MobileNetworkOperator *string `json:"mobileNetworkOperator,omitempty"`
	// Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
	RequestID string `json:"requestId"`
	// Prove-issued unique, private key that identifies Sub Client.
	SubClientID *string `json:"subClientId,omitempty"`
	// A unique identifier for our customer's subscribers for Identity Manager.
	SubscriptionCustomerID *string `json:"subscriptionCustomerId,omitempty"`
}
