// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RedirectFinishRequest struct {
	// Prove-issued unique, private key that identifies the API Client.
	APIClientID string `json:"apiClientId"`
	// Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
	//
	RequestID string `json:"requestId"`
	// Prove-issued unique, private key that identifies Sub Client.
	SubClientID *string `json:"subClientId,omitempty"`
	// The VFP value returned by the mobile device after authentication.
	VerificationFingerprint string `json:"verificationFingerprint"`
}
