// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ScoreRequest struct {
	// Denotes whether consent has been provided by the mobile subscriber for this transaction. Acceptable values are:
	// - `optedIn` - The end user has provided consent for the collection of their personal data. - `optedOut` - The end user has refused to allow collection of their personal data. - `notCollected` - No attempt has been made to obtain consent from the end user. - `unknown` - The status of consent collection is unknown.
	// Note: This value must be optedIn in order to access MNO data. Legacy customers' configurations are not affected by this requirement at this time.
	ConsentStatus ConsentStatus `json:"consentStatus"`
	// True indicates whether the client is accessing premium data responses. See Response Definitions for examples with and without details.
	Details *string `json:"details,omitempty"`
	// A persistent ID that uniquely identifies a telephone subscriber. A phoneNumber or payfoneAlias is required in the request, not both.
	PayfoneAlias *string `json:"payfoneAlias,omitempty"`
	// The phone number being queried. Formatted in E.164 formatting for international numbers including the leading plus sign.
	PhoneNumber string `json:"phoneNumber"`
	// Unique identifier associated with this request. This identifier must be unique for each transaction. The RequestId input field is rejected as invalid if it contains any special characters other than dashes, periods, underbars, plus signs, equal signs, or forward slashes. Max length is 128 bytes.
	RequestID string `json:"requestId"`
	// A unique identifier for our customer's subscribers for Identity Manager.
	SubscriptionCustomerID *string `json:"subscriptionCustomerId,omitempty"`
}
