// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VerifyRequest struct {
	// The address number and street associated with the phone number being queried.
	Address *string `json:"address,omitempty"`
	// The city associated with the phone number.
	City *string `json:"city,omitempty"`
	// Denotes whether consent has been provided by the mobile subscriber for this transaction. Acceptable values are:
	// - `optedIn` - The end user has provided consent for the collection of their personal data. - `optedOut` - The end user has refused to allow collection of their personal data. - `notCollected` - No attempt has been made to obtain consent from the end user. - `unknown` - The status of consent collection is unknown.
	// Note: This value must be optedIn in order to access MNO data. Legacy customers' configurations are not affected by this requirement at this time.
	ConsentStatus *ConsentStatus `json:"consentStatus,omitempty"`
	// True indicates whether the client is accessing premium data responses.
	Details *string `json:"details,omitempty"`
	// Date of birth associated with the phone number.
	Dob *string `json:"dob,omitempty"`
	// The driver's license number associated with the phone number and person being queried.
	DriversLicenseNumber *string `json:"driversLicenseNumber,omitempty"`
	// The driver's license state associated with the phone number and person being queried.
	DriversLicenseState *string `json:"driversLicenseState,omitempty"`
	// Email associated with the phone number.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// The second line of the address associated with the phone number being queried.
	ExtendedAddress *string `json:"extendedAddress,omitempty"`
	// First name associated with the phone number being queried.
	FirstName string `json:"firstName"`
	// The last four of the social security number associated with the subscriber.
	Last4 *string `json:"last4,omitempty"`
	// Last name associated with the phone number being queried.
	LastName string `json:"lastName"`
	// Date in which the identity behind the phone number was last verified.
	LastVerified *string `json:"lastVerified,omitempty"`
	// A persistent ID that uniquely identifies a telephone subscriber. A phoneNumber or payfoneAlias is required in the request, not both.
	PayfoneAlias *string `json:"payfoneAlias,omitempty"`
	// The phone number being queried. Formatted in E.164 formatting for international numbers including the leading plus sign.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// If set to true, the phoneUpdate object will be included in the response if the phone number being queried has changed since the lastVerified date.
	PhoneUpdate *string `json:"phoneUpdate,omitempty"`
	// The postal code associated with the phone number.
	PostalCode *string `json:"postalCode,omitempty"`
	// The region (or state abbreviation) associated with the phone number.
	Region *string `json:"region,omitempty"`
	// Unique identifier associated with this request. This identifier must be unique for each transaction.
	RequestID string `json:"requestId"`
	// The social security number associated with the subscriber.
	Ssn *string `json:"ssn,omitempty"`
	// A unique identifier for our customer's subscribers for Identity Manager.
	SubscriptionCustomerID *string `json:"subscriptionCustomerId,omitempty"`
}
